<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ScienceGroupAddMemberButton</name>
   <tag></tag>
   <elementGuidId>f461a83e-9d6c-4631-86be-7e960a2eb4fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick=&quot;$('.invite-block').closest('.tipsy').remove();$(this).tipsy('show');&quot;])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>left-nav-invite lsb-add-member-btn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$('.invite-block').closest('.tipsy').remove();$(this).tipsy('show');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>original-title</name>
      <type>Main</type>
      <value>&lt;a class=&quot;invite-close&quot;>x&lt;/a>&lt;br />&lt;span class=&quot;head&quot;>Send Invite&lt;/span> &lt;div class=&quot;invite-block&quot;>&lt;a class=&quot;invite-link&quot; onclick=&quot;elgg.groups.generate_invitecode('25776662', 'member_25776662_326309857', 'yes', 'get_invitecode');$('.invite-block').closest('.tipsy').remove();&quot;>Invite Parent(s) using group code&lt;/a>&lt;a class=&quot;invite-link default_invite_25776662&quot; onclick=&quot;elgg.groups.group_send_invite('25776662', function() { $('.invite-block').closest('.tipsy').remove();elgg.groups.show_invite_popup('member_25776662_326309857','Science as a Parent', 'yes') })&quot;>Invite Parent(s) via e-mail&lt;/a>&lt;a class=&quot;invite-link&quot; onclick=&quot;elgg.groups.generate_invitecode('25776662', 'member_25776662_1031478429_srw', 'yes', 'get_invitecode');$('.invite-block').closest('.tipsy').remove();&quot;>Invite Student(s) using group code&lt;/a>&lt;a class=&quot;invite-link default_invite_25776662&quot; onclick=&quot;elgg.groups.group_send_invite('25776662', function() { $('.invite-block').closest('.tipsy').remove();elgg.groups.show_invite_popup('member_25776662_1031478429_srw','Science as a Student', 'yes') })&quot;>Invite Student(s) via e-mail&lt;/a>&lt;/div></value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Member</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elgg-group-25776662&quot;)/div[@class=&quot;elgg-image-block clearfix&quot;]/div[@class=&quot;elgg-body&quot;]/div[@class=&quot;ul-div  -- 3&quot;]/div[@class=&quot;div-right&quot;]/a[@class=&quot;left-nav-invite lsb-add-member-btn&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick=&quot;$('.invite-block').closest('.tipsy').remove();$(this).tipsy('show');&quot;])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='elgg-group-25776662']/div/div/div[2]/div[2]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Science'])[2]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='schoolofindia'])[2]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[2]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li/div/div/div[2]/div[2]/a</value>
   </webElementXpaths>
</WebElementEntity>
